# https://github.com/elastic/kibana-docker
# `kibana-oss` excludes the free commercial xpack license
FROM docker.elastic.co/kibana/kibana:6.6.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
