# https://github.com/elastic/elasticsearch-docker
# `elasticsearch-oss` is the pure Apache License version
FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.1

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
