# https://github.com/elastic/logstash-docker
# `logstash-oss` has no free xpack
FROM docker.elastic.co/logstash/logstash:6.6.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
